spring:
  application:
    name: team3-coupon

  # === [기존 H2 설정 주석 보존] ===
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console # 콘솔 접속 URL 경로
  #  datasource:
  #    # JDBC URL 설정 (인메모리 데이터베이스는 보통 이 설정을 사용하며, URL을 명시적으로 지정해주는 것이 좋습니다.)
  #    url: jdbc:h2:mem:coupon_db
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password:

  # === [MySQL DB 설정 추가] ===
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/project_be12_team3?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: project_be12_team3
    password: Vu52gc0i(mNxDJyI
    driver-class-name: com.mysql.cj.jdbc.Driver

  # === [JPA 설정 추가] ===
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs  # OpenAPI JSON 경로
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 경로
    tags-sorter: alpha  # 태그 알파벳 순 정렬
    operations-sorter: alpha  # API 알파벳 순 정렬

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true # 유레카 서버에 등록할지 여부
    fetch-registry: true # 유레카 서버의 정보를 가져올지 여부
    service-url:
      # 유레카 client와 server를 연결하는 url 주소
      defaultZone: http://team3-eureka:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: "v3s5v8y/B?E(H+MbQeThWmZq4t7w9z$C&F)J@NcRfUjXn2r5u8x/A?D(G+KaPdSg"